### PR TITLE
Add property "s3BucketName" to god tools properties file

### PR DESCRIPTION
**Pull request by ryancarlson**
Used to specify stage or production bucket at runtime

### CODE REVIEW

**Comment by ryancarlson** [comment]
@twinge one liner here.

**Comment by ryancarlson** [comment]
I need this to deploy to stage... so merging now.

**Comment by ryancarlson** [comment]
@twinge this is ready to go to prod... speak now or forever hold your peace :)

**Comment by twinge** [comment]
Is chef still a thing?

**Comment by ryancarlson** [comment]
Is that a serious question?

**Comment by twinge** [comment]
No

**Pull request merged**
