### PR TITLE
Update godtools_api_properties.xml.erb

### PR DESCRIPTION
**Pull request by twinge**
Get memcached host value from stack json

### CODE REVIEW

**Comment by twinge** [comment]
@ryancarlson

**Comment by ryancarlson** [comment]
Is the elasticache IP address fixed or dynamic?

**Comment by twinge** [comment]
I updated the stack json. The elasticache host is
sessions.t5vw3x.cfg.use1.cache.amazonaws.com. It's a dns entry, so the
underlying server can change, but the value is static.

**Comment by ryancarlson** [comment]
Sweet.  And you said there's "plenty of headroom".. can you quantify that?  Ballpark is fine.

**Comment by twinge** [comment]
~1.5gb

**Comment by ryancarlson** [comment]
:+1:

**Pull request merged**
