### PR TITLE
ERT SMTP port

### PR DESCRIPTION
**Pull request by ryancarlson**
- add a property where the SMTP port can be overridden for ERT
- revert an experimental commit that was used in ERT stage to test setting a server env variable

### CODE REVIEW

**Comment by ryancarlson** [comment]
@twinge @mattdrees... jump ball!

**Comment by mattdrees** [comment]
looks fine to me, though I'm surely a newb with chef scripts

**Comment by ryancarlson** [comment]
Yeah, it's just adding a field, and reverting a temporary commit.  Nothing too serious here... :)

**Comment by ryancarlson** [comment]
I'll deploy to stage first and make sure it all works correctly, and that we can actually communicate with SES over the port they suggest

**Pull request merged**
