### PR TITLE
Add a template file for standalone.conf

### PR DESCRIPTION
**Pull request by ryancarlson**
- in this file contains parameters to set initial & max heap size as well as max permgen space
- these values will be passed in as parameters from stack JSON
- going to try:
  - initial heap 512m
  - max heap 3072m
  - max permgen 2048m

This should help with, but not totally solve, some memory issues that crop up from time to time.

Specifically...
- the god tools webapp contractors killed the stage server with a blast of large requests that certainly filled the heap which maxed at 512m
- repeated deployments will max out permgen space.  this just buys a little more time until a new (Docker!) solution is implemented

### CODE REVIEW

**Comment by ryancarlson** [comment]
@mattdrees @twinge @sbratton have a second to look at this?

**Comment by mattdrees** [comment]
It would be nice if you had two commits; one with a standalone.conf.erb identical to wildfly's default standalone.conf, and a second one that makes whatever change you are needing. As is, I can't easily tell what is different.

**Comment by mattdrees** [comment]
Also, I don't know much about how environment variables work in Opsworks, but GCE/Docker uses them quite a bit for config. Is it possible to use Opsworks to set up whatever JAVA_OPTS environment variable you need, instead of using standalone.conf to do it? That might make it easier to transition to GCE/Docker.

**Comment by ryancarlson** [comment]
@mattdrees hey sorry this one slipped off my radar for a few days (week).  i redid the commits so it would be easier to review.

I don't have an answer towards using OpsWorks to manipulate JAVA_OPTS to do this.  I think that would be worthwhile to investigate when we get to moving this to GCE/Docker, but for now I'm comfortable with a change that I know will work in the OpsWorks world.

**Comment by ryancarlson** [comment]
@mattdrees  bump

**Comment by mattdrees** [comment]
Thanks for the separate commits.

Aside from the MaxPermGen issue, looks good to me.

**Comment by ryancarlson** [comment]
fixed that default... thanks for the review!

**Pull request merged**
