### PR TITLE
Set ssl parameter to true

### PR DESCRIPTION
**Pull request by ryancarlson**
since new jenkins server is requiring SSL

### CODE REVIEW

**Comment by ryancarlson** [comment]
@twinge ?

**Comment by ryancarlson** [comment]
ref: https://github.com/arangamani/jenkins_api_client/blob/master/lib/jenkins_api_client/client.rb#L68

**Comment by twinge** [comment]
:+1:

**Comment by ryancarlson** [comment]
thanks!

**Pull request merged**
